"""empty message

Revision ID: 17da8705f1b9
Revises: a11646878e2d
Create Date: 2020-01-16 07:46:13.627981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17da8705f1b9'
down_revision = 'a11646878e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
